name: CrestBank
version: ${project.version}
main: net.crestbank.money.Money
api-version: 1.20
depend: [Vault]
softdepend: [PlaceholderAPI]
commands:
  bank:
    description: Main command for CrestBank
    usage: /bank
    permission: crestbank.user
permissions:
  crestbank.user:
    description: Allows use of basic bank features
    default: true
  crestbank.admin:
    description: Allows use of administrative bank features
    default: op
